v0.6-RC5.3
### app/api.py
- simplify json return
{
error: int | error code
msg: str | human readable error message
time: obj | datetime object
eventid: str | event id from frigate
camera: str | camera name from frigate
object: str | object type from frigate
score: int | score from frigate
}

### app/mqtt_client
- refactor addEventResponseJSON to respJSON
- instead of looking for respJSON["msg"] it now evaluates respJSON["error"]
- on error != 0 it outputs respJSON using logit.execute().